### ISSUE TITLE
Support for Chimera

### ISSUE THREAD

**Issue by rui-ribeiro** [gliwka/hyperscan-java#117]
Hello,

I would like to start by saying that this project is great!

I was wondering tho if there are any plans for supporting the Chimera "plug-in". I tried t find references of it but I was unsuccessful. 

Thanks!

**Comment by gliwka** [comment]
Chimera uses hyperscan to match regular expression using the PREFILTER flag, then passes the expressions into PCRE for confirmation.

I'm currently doing the same in one of my projects without chimera, by using the PREFILTER flag in combination with normal Java Regex API instead of PCRE. This allows me to have similar performance benefits while having the advantage that I can use the regular Java Regex API. The code basically returns a list of suitable [Matchers](https://docs.oracle.com/javase/7/docs/api/java/util/regex/Matcher.html) and I can use the regular Java API to get matches.

Would this be of interest to you? I could extract this code and put it into this library to enable this use case.

**Comment by rui-ribeiro** [comment]
Oh, that is a great piece of information! I totally missed that flag, thank you 👍 

One thing tho, I still require to be able to run PCRE and I believe the standard Java Regex library doesn't support it, right?

**Comment by gliwka** [comment]
Yes, there are some small differences: https://gist.github.com/CMCDragonkai/6c933f4a7d713ef712145c5eb94a1816

I will add my utility code to the repository.

Feel free to submit a pull request for chimera support.

**Comment by gliwka** [comment]
Version 5.4.0-2.0.0 now has the PatternFilter (see README), which is similar to chimera, only more convenient with Java APIs. Please submit a Pull Request, if you need chimera.

**Comment by rui-ribeiro** [comment]
Thanks for adding it so quickly! Really appreciate it 💯 

I'm gonna think about Chimera, I'm not sure yet where to start.
