### ISSUE TITLE
get the index id of Expressions

### ISSUE THREAD

**Issue by tuian** [gliwka/hyperscan-java#56]
### 0x00 getMatchedExpressionId
such as, getMatchedExpressionId fuction.

like hyperscan python:

```c
def done(eid, start, end, flags, context):
    """
    On a found result:
        -Expression ID
        -Start Offset
        -End Offset
        -Flags (Currently Unused)
        -Context object passed to scan
    """
   print(eid)

db.scan(log_strings, match_event_handler=done, context={'offset': offset, "rawlog": rawlog})
```

**Comment by gliwka** [comment]
The call to scan returns a list of matches:

```java
List<Match> matches = scanner.scan(db, "12345 test string");
```

A match returns the matched string, start of match, end of match and the matching expression directly instead of the id (see https://github.com/gliwka/hyperscan-java/blob/develop/src/main/java/com/gliwka/hyperscan/wrapper/Match.java - getMatchedExpression). 

This makes the ids obsolete, since you can retrieve the matching expression directly.

Does this suite your use case? Or do you need the ids for a different purpose?
